'use client';

import { useState } from 'react';
import { Bell, BriefcaseBusiness, ChevronDown, Clock3, Command, FileText, LayoutDashboard, MapPin, Search, Settings2, Sparkles, Target, Users } from 'lucide-react';

const jobs = [
  { company: 'Stripe', mark: 'S', role: 'Software Engineering Intern', meta: 'San Francisco, CA · Hybrid', tags: ['Backend', 'Java', 'Distributed systems'], age: '12m', color: '#6c5ce7' },
  { company: 'Figma', mark: 'F', role: 'Frontend Engineering Intern', meta: 'New York, NY · Hybrid', tags: ['Frontend', 'React', 'TypeScript'], age: '24m', color: '#f24e1e' },
  { company: 'Anthropic', mark: 'A', role: 'ML Systems Intern', meta: 'San Francisco, CA · On-site', tags: ['ML', 'Python', 'PyTorch'], age: '31m', color: '#bd7652' },
  { company: 'Vercel', mark: 'V', role: 'Full Stack Engineering Intern', meta: 'Remote · US', tags: ['Full stack', 'Next.js', 'Postgres'], age: '46m', color: '#111827' },
  { company: 'Ramp', mark: 'R', role: 'Software Engineer Intern', meta: 'New York, NY · On-site', tags: ['Backend', 'Go', 'Fintech'], age: '1h', color: '#14a97b' },
];
const nav = [[LayoutDashboard, 'Overview'], [Search, 'Discover'], [BriefcaseBusiness, 'Applications'], [Target, 'Watchlists'], [Users, 'People'], [FileText, 'Documents']] as const;

export default function Home() {
  const [selected, setSelected] = useState(0);
  const [active, setActive] = useState('Discover');
  const job = jobs[selected];
  return <main className="app-shell">
    <aside className="sidebar"><div className="brand"><span className="brand-mark">O</span><span>Orbit</span></div>
      <nav className="nav-list" aria-label="Main navigation"><p className="nav-label">Workspace</p>{nav.map(([Icon,label]) => <button key={label} className={active===label?'nav-item active':'nav-item'} onClick={()=>setActive(label)}><Icon size={17}/><span>{label}</span>{label==='Discover'&&<b>28</b>}</button>)}</nav>
      <div className="sidebar-footer"><button className={active==='Preferences'?'nav-item active':'nav-item'} onClick={()=>setActive('Preferences')}><Settings2 size={17}/><span>Preferences</span></button><div className="user"><span>MS</span><div><strong>Meghana</strong><small>Summer 2027 search</small></div><ChevronDown size={15}/></div></div>
    </aside>
    <section className="workspace"><header className="topbar"><div className="global-search"><Search size={17}/><input aria-label="Search opportunities" placeholder="Search roles, companies, skills…"/><kbd><Command size={12}/> K</kbd></div><div className="top-actions"><span className="sync"><i/>Synced 2m ago</span><button className="icon-button" aria-label="Notifications"><Bell size={18}/><em/></button><button className="primary-button"><Sparkles size={15}/> Tune your search</button></div></header>
      <div className="content">{active==='Applications'?<Applications/>:active==='Overview'?<Overview/>:active==='Preferences'?<Preferences/>:<><div className="page-heading"><div><p className="eyebrow">YOUR 2027 OPPORTUNITY RADAR</p><h1>{active}</h1><p>Every relevant internship, ranked and explained.</p></div><div className="heading-stat"><span>28</span><small>new since<br/>last visit</small></div></div>
        <div className="filters"><button className="filter active">All roles <span>184</span></button><button className="filter">Summer 2027 <ChevronDown size={13}/></button><button className="filter">US + Remote <ChevronDown size={13}/></button><button className="filter">Role family <ChevronDown size={13}/></button><button className="filter"><Settings2 size={14}/> More filters</button></div>
        <div className="dashboard-grid"><section className="job-panel"><div className="panel-head"><span>184 opportunities</span><button>Best match <ChevronDown size={13}/></button></div><div className="job-list">{jobs.map((item,index)=><button key={item.company} className={selected===index?'job-card selected':'job-card'} onClick={()=>setSelected(index)}><span className="company-logo" style={{background:item.color}}>{item.mark}</span><div className="job-copy"><div><strong>{item.company}</strong><time><Clock3 size={12}/>{item.age}</time></div><h3>{item.role}</h3><p><MapPin size={12}/>{item.meta}</p><div>{item.tags.map(tag=><span key={tag}>{tag}</span>)}</div></div>{index<3&&<i className="new-dot"/>}</button>)}</div></section>
          <section className="detail-card"><div className="detail-top"><span className="company-logo large" style={{background:job.color}}>{job.mark}</span><div><small>TOP MATCH · 94%</small><h2>{job.role}</h2><p>{job.company} · {job.meta}</p></div><button>Save</button></div><div className="detail-tabs"><button className="active">Brief</button><button>Job description</button><button>People & resumes</button><button>Company signal</button></div>
            <div className="insight-callout"><Sparkles size={17}/><div><strong>Why this is a strong match</strong><p>Your backend projects and Java experience align with 7 of 9 core requirements. The Payments Infrastructure team is growing after a recent product expansion.</p></div></div>
            <div className="two-col"><div><h4>What matters in this role</h4><ul className="check-list"><li>Build high-scale payment APIs</li><li>Own systems from design to production</li><li>Work across Java, Ruby, and Go</li></ul></div><div><h4>Important keywords</h4><div className="keyword-cloud"><span>distributed systems</span><span>Java</span><span>APIs</span><span>SQL</span><span>ownership</span><span>reliability</span></div></div></div>
            <div className="people-row"><div><h4>Past interns found</h4><p>Public profiles associated with this team</p></div><div className="avatars"><span>AK</span><span>JL</span><span>RM</span><b>+8</b></div><button>Explore people →</button></div><div className="action-row"><button className="secondary-button">Add to tracker</button><button className="primary-button">View & apply ↗</button></div>
          </section>
          <aside className="insights-rail"><div className="metric-card"><div><span>Pipeline</span><button>View all</button></div><strong>12</strong><small>active applications</small><div className="mini-bars"><i style={{height:'36%'}}/><i style={{height:'52%'}}/><i style={{height:'45%'}}/><i style={{height:'72%'}}/><i style={{height:'62%'}}/><i style={{height:'88%'}}/><i style={{height:'100%'}}/></div><p><b>3</b> need your attention this week</p></div><div className="alert-card"><div className="alert-icon"><Bell size={15}/></div><strong>Fresh-role alerts are on</strong><p>We scan free public sources every 30 minutes for your target roles.</p><button>Manage alerts</button></div><div className="signal-card"><p>MARKET SIGNAL</p><strong>ML infrastructure roles <em>↑ 18%</em></strong><span>More 2027 postings mention evaluation, inference, and data platforms this week.</span></div></aside>
        </div></>}
      </div>
    </section>
  </main>;
}

function Applications(){
  const columns=[
    {name:'Saved',count:6,cards:[['Figma','Frontend Engineering Intern','New York · Summer 2027','2d'],['Datadog','Software Engineer Intern','Boston · Summer 2027','3d']]},
    {name:'Applied',count:4,cards:[['Stripe','Software Engineering Intern','San Francisco · Summer 2027','Aug 28'],['Ramp','Backend Engineering Intern','New York · Fall 2027','Aug 25']]},
    {name:'Interviewing',count:2,cards:[['Notion','Software Engineer Intern','San Francisco · Summer 2027','Sep 4'],['Cloudflare','Systems Engineering Intern','Austin · Summer 2027','Sep 6']]},
    {name:'Offer',count:1,cards:[['Linear','Product Engineering Intern','Remote · Summer 2027','Review by Sep 9']]},
  ];
  return <><div className="page-heading"><div><p className="eyebrow">APPLICATION WORKSPACE</p><h1>Applications</h1><p>One place for every deadline, follow-up, and outcome.</p></div><button className="primary-button">+ Add application</button></div><div className="tracker-summary"><div><b>13</b><span>Total tracked</span></div><div><b>8</b><span>Applications sent</span></div><div><b>25%</b><span>Interview rate</span></div><div><b>2</b><span>Actions due</span></div></div><div className="kanban">{columns.map(col=><section className="kanban-col" key={col.name}><header><span><i/> {col.name}</span><b>{col.count}</b></header>{col.cards.map(card=><article className="application-card" key={card[0]}><div><span className="tiny-logo">{card[0][0]}</span><b>{card[0]}</b><button>•••</button></div><h3>{card[1]}</h3><p>{card[2]}</p><footer><span>{col.name==='Interviewing'?'Upcoming':'Updated'} · {card[3]}</span></footer></article>)}<button className="add-card">+ Add application</button></section>)}</div></>;
}

function Overview(){return <><div className="page-heading"><div><p className="eyebrow">SEARCH PERFORMANCE</p><h1>Your search, at a glance</h1><p>Signals that help you spend time on the right opportunities.</p></div><button className="filter">Last 30 days <ChevronDown size={13}/></button></div><div className="overview-cards"><div><span>Relevant roles found</span><b>184</b><em>↑ 34 this week</em></div><div><span>Applications sent</span><b>8</b><em>4.3% of matches</em></div><div><span>Interview rate</span><b>25%</b><em>↑ 9% vs. average</em></div><div><span>Avg. match score</span><b>86%</b><em>Strong fit</em></div></div><div className="analytics-grid"><section className="chart-card"><header><div><b>Opportunity momentum</b><span>New relevant roles discovered</span></div><div className="legend"><i/> Summer 2027 <i/> Fall 2027</div></header><div className="line-chart"><svg viewBox="0 0 700 220" preserveAspectRatio="none"><path d="M0 180 C90 165 90 120 170 135 S280 170 350 105 S455 72 520 90 S620 35 700 44" fill="none" stroke="#176b53" strokeWidth="3"/><path d="M0 195 C100 185 120 175 190 180 S300 150 360 165 S480 130 540 145 S650 110 700 118" fill="none" stroke="#a9c8ba" strokeWidth="3"/></svg><div><span>Aug 1</span><span>Aug 8</span><span>Aug 15</span><span>Aug 22</span><span>Aug 29</span></div></div></section><section className="chart-card"><header><div><b>Roles by focus</b><span>Your current opportunity mix</span></div></header><div className="role-bars">{[['Backend',42],['Full stack',31],['Machine learning',27],['Frontend',19],['Generic SDE',65]].map(([name,val])=><div key={name}><span>{name}</span><i><b style={{width:`${Number(val)*1.45}%`}}/></i><em>{val}</em></div>)}</div></section></div></>}

function Preferences(){const [days,setDays]=useState('365');return <><div className="page-heading"><div><p className="eyebrow">WORKSPACE SETTINGS</p><h1>Preferences</h1><p>Control your search, alerts, and data lifecycle.</p></div></div><div className="settings-card"><section><div><h3>Data retention</h3><p>Choose how long closed applications, activity history, and cached job details remain available.</p></div><select value={days} onChange={e=>setDays(e.target.value)}><option value="90">90 days</option><option value="180">180 days</option><option value="365">1 year</option><option value="forever">Keep until I delete</option></select></section><section><div><h3>Discovery refresh</h3><p>Scan supported public job sources for newly posted or changed roles.</p></div><span className="setting-value">Every 30 minutes</span></section><section><div><h3>Duplicate detection</h3><p>Merge reposted roles across company boards and aggregators.</p></div><button className="toggle on"><i/></button></section><section><div><h3>Opportunity alerts</h3><p>Highlight strong matches and roles that may close quickly.</p></div><button className="toggle on"><i/></button></section></div><div className="settings-note"><strong>Your data stays yours.</strong><p>Retention changes apply to future cleanup runs. Public-source snapshots are removed with their related opportunity records.</p></div></>}
