'use client';

import { FormEvent, useEffect, useMemo, useState } from 'react';
import { Bell, BriefcaseBusiness, ChevronDown, Clock3, Command, FileText, LayoutDashboard, MapPin, Search, Settings2, Sparkles, Target, Users, X } from 'lucide-react';

type Status = 'Saved'|'Applied'|'Interviewing'|'Offer';
type Application = {id:string;company:string;role:string;location:string;status:Status;updated:string};
type Job = {company:string;mark:string;role:string;meta:string;tags:string[];age:string;color:string;apply:string};

const jobs:Job[] = [
  {company:'Stripe',mark:'S',role:'Software Engineering Intern',meta:'San Francisco, CA · Hybrid',tags:['Backend','Java','Distributed systems'],age:'12m',color:'#6c5ce7',apply:'https://stripe.com/jobs/search'},
  {company:'Figma',mark:'F',role:'Frontend Engineering Intern',meta:'New York, NY · Hybrid',tags:['Frontend','React','TypeScript'],age:'24m',color:'#f24e1e',apply:'https://www.figma.com/careers/'},
  {company:'Anthropic',mark:'A',role:'ML Systems Intern',meta:'San Francisco, CA · On-site',tags:['ML','Python','PyTorch'],age:'31m',color:'#bd7652',apply:'https://www.anthropic.com/careers'},
  {company:'Vercel',mark:'V',role:'Full Stack Engineering Intern',meta:'Remote · US',tags:['Full stack','Next.js','Postgres'],age:'46m',color:'#111827',apply:'https://vercel.com/careers'},
  {company:'Ramp',mark:'R',role:'Software Engineer Intern',meta:'New York, NY · On-site',tags:['Backend','Go','Fintech'],age:'1h',color:'#14a97b',apply:'https://www.ramp.com/careers'},
];
const nav = [[LayoutDashboard,'Overview'],[Search,'Discover'],[BriefcaseBusiness,'Applications'],[Target,'Watchlists'],[Users,'People'],[FileText,'Documents']] as const;
const statuses:Status[]=['Saved','Applied','Interviewing','Offer'];

export default function Home(){
  const [active,setActive]=useState('Discover');
  const [selected,setSelected]=useState(0);
  const [query,setQuery]=useState('');
  const [detailTab,setDetailTab]=useState('Brief');
  const [saved,setSaved]=useState<string[]>([]);
  const [apps,setApps]=useState<Application[]>([]);
  const [modal,setModal]=useState(false);
  const [toast,setToast]=useState('');
  const [draft,setDraft]=useState({company:'',role:'',location:'',status:'Applied' as Status});
  useEffect(()=>{try{setApps(JSON.parse(localStorage.getItem('orbit-applications')||'[]'));setSaved(JSON.parse(localStorage.getItem('orbit-saved')||'[]'))}catch{}},[]);
  useEffect(()=>{localStorage.setItem('orbit-applications',JSON.stringify(apps))},[apps]);
  useEffect(()=>{localStorage.setItem('orbit-saved',JSON.stringify(saved))},[saved]);
  useEffect(()=>{if(!toast)return;const id=setTimeout(()=>setToast(''),2600);return()=>clearTimeout(id)},[toast]);
  const visible=useMemo(()=>jobs.filter(j=>(j.company+' '+j.role+' '+j.tags.join(' ')).toLowerCase().includes(query.toLowerCase())),[query]);
  const job=jobs[selected]||jobs[0];
  const openForm=(source?:Job,status:Status='Applied')=>{setDraft({company:source?.company||'',role:source?.role||'',location:source?.meta||'',status});setModal(true)};
  const addApplication=(e:FormEvent)=>{e.preventDefault();if(!draft.company.trim()||!draft.role.trim())return;setApps(v=>[{id:crypto.randomUUID(),...draft,updated:'Just now'},...v]);setModal(false);setActive('Applications');setToast('Application added to your tracker')};
  const updateStatus=(id:string,status:Status)=>{setApps(v=>v.map(a=>a.id===id?{...a,status,updated:'Just now'}:a));setToast(`Moved to ${status}`)};
  const removeApp=(id:string)=>{setApps(v=>v.filter(a=>a.id!==id));setToast('Application removed')};
  const toggleSaved=()=>{setSaved(v=>v.includes(job.company)?v.filter(x=>x!==job.company):[...v,job.company]);setToast(saved.includes(job.company)?'Removed from saved roles':'Role saved')};
  const go=(page:string)=>{setActive(page);if(page==='Applications')setDetailTab('Brief')};

  return <main className="app-shell">
    <aside className="sidebar"><div className="brand"><span className="brand-mark">O</span><span>Orbit</span></div><nav className="nav-list" aria-label="Main navigation"><p className="nav-label">Workspace</p>{nav.map(([Icon,label])=><button key={label} className={active===label?'nav-item active':'nav-item'} onClick={()=>go(label)}><Icon size={17}/><span>{label}</span>{label==='Applications'&&apps.length>0&&<b>{apps.length}</b>}</button>)}</nav><div className="sidebar-footer"><button className={active==='Preferences'?'nav-item active':'nav-item'} onClick={()=>go('Preferences')}><Settings2 size={17}/><span>Preferences</span></button><div className="user"><span>MS</span><div><strong>Meghana</strong><small>Summer 2027 search</small></div><ChevronDown size={15}/></div></div></aside>
    <section className="workspace"><header className="topbar"><div className="global-search"><Search size={17}/><input aria-label="Search opportunities" value={query} onChange={e=>{setQuery(e.target.value);setActive('Discover')}} placeholder="Search roles, companies, skills…"/><kbd><Command size={12}/> K</kbd></div><div className="top-actions"><span className="sync"><i/>Synced 2m ago</span><button className="icon-button" aria-label="Notifications" onClick={()=>setToast('You have no new notifications')}><Bell size={18}/></button><button className="primary-button" onClick={()=>go('Preferences')}><Sparkles size={15}/> Tune your search</button></div></header>
      <div className="content">{active==='Applications'?<Applications apps={apps} openForm={openForm} updateStatus={updateStatus} removeApp={removeApp}/>:active==='Overview'?<Overview apps={apps}/>:active==='Preferences'?<Preferences toast={setToast}/>:active==='Discover'?<Discover visible={visible} job={job} selected={selected} select={i=>{setSelected(jobs.indexOf(visible[i]));setDetailTab('Brief')}} tab={detailTab} setTab={setDetailTab} saved={saved.includes(job.company)} toggleSaved={toggleSaved} openForm={openForm} go={go}/>:<SimplePage name={active} go={go}/>}</div>
    </section>
    {modal&&<div className="modal-backdrop" onMouseDown={()=>setModal(false)}><form className="application-modal" onSubmit={addApplication} onMouseDown={e=>e.stopPropagation()}><header><div><p className="eyebrow">APPLICATION TRACKER</p><h2>Add an application</h2></div><button type="button" aria-label="Close" onClick={()=>setModal(false)}><X size={18}/></button></header><label>Company<input autoFocus value={draft.company} onChange={e=>setDraft({...draft,company:e.target.value})} required/></label><label>Role<input value={draft.role} onChange={e=>setDraft({...draft,role:e.target.value})} required/></label><label>Location<input value={draft.location} onChange={e=>setDraft({...draft,location:e.target.value})}/></label><label>Status<select value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value as Status})}>{statuses.map(s=><option key={s}>{s}</option>)}</select></label><footer><button type="button" className="secondary-button" onClick={()=>setModal(false)}>Cancel</button><button className="primary-button" type="submit">Add to tracker</button></footer></form></div>}
    {toast&&<div className="toast-message" role="status">✓ {toast}</div>}
  </main>
}

function Discover({visible,job,selected,select,tab,setTab,saved,toggleSaved,openForm,go}:{visible:Job[];job:Job;selected:number;select:(i:number)=>void;tab:string;setTab:(x:string)=>void;saved:boolean;toggleSaved:()=>void;openForm:(j?:Job,s?:Status)=>void;go:(x:string)=>void}){
  return <><div className="page-heading"><div><p className="eyebrow">YOUR 2027 OPPORTUNITY RADAR</p><h1>Discover</h1><p>Every relevant internship, ranked and explained.</p></div><div className="heading-stat"><span>{visible.length}</span><small>matching<br/>roles</small></div></div><div className="filters"><button className="filter active">All roles <span>{visible.length}</span></button><button className="filter" onClick={()=>{}}>Summer 2027 ✓</button><button className="filter" onClick={()=>{}}>US + Remote ✓</button><button className="filter" onClick={()=>{}}>All role families ✓</button><button className="filter" onClick={()=>go('Preferences')}><Settings2 size={14}/> More filters</button></div>
    <div className="dashboard-grid"><section className="job-panel"><div className="panel-head"><span>{visible.length} opportunities</span><button onClick={()=>{}}>Best match <ChevronDown size={13}/></button></div><div className="job-list">{visible.length?visible.map((item,index)=><button key={item.company} className={jobs[selected]?.company===item.company?'job-card selected':'job-card'} onClick={()=>select(index)}><span className="company-logo" style={{background:item.color}}>{item.mark}</span><div className="job-copy"><div><strong>{item.company}</strong><time><Clock3 size={12}/>{item.age}</time></div><h3>{item.role}</h3><p><MapPin size={12}/>{item.meta}</p><div>{item.tags.map(t=><span key={t}>{t}</span>)}</div></div></button>):<div className="empty-inline">No roles match your search.</div>}</div></section>
      <section className="detail-card"><div className="detail-top"><span className="company-logo large" style={{background:job.color}}>{job.mark}</span><div><small>TOP MATCH · 94%</small><h2>{job.role}</h2><p>{job.company} · {job.meta}</p></div><button onClick={toggleSaved}>{saved?'Saved ✓':'Save'}</button></div><div className="detail-tabs">{['Brief','Job description','People & resumes','Company signal'].map(t=><button key={t} className={tab===t?'active':''} onClick={()=>setTab(t)}>{t}</button>)}</div><DetailContent tab={tab} job={job}/><div className="action-row"><button className="secondary-button" onClick={()=>openForm(job,'Saved')}>Add to tracker</button><button className="primary-button" onClick={()=>window.open(job.apply,'_blank','noopener,noreferrer')}>View & apply ↗</button></div></section>
      <aside className="insights-rail"><div className="metric-card"><div><span>Pipeline</span><button onClick={()=>go('Applications')}>View all</button></div><strong>0</strong><small>active applications</small><div className="mini-bars">{[1,2,3,4,5,6,7].map(i=><i key={i} style={{height:'4%'}}/>)}</div><p>Add your first application to start tracking.</p></div><div className="alert-card"><div className="alert-icon"><Bell size={15}/></div><strong>Fresh-role alerts are on</strong><p>We scan public sources every 30 minutes for your target roles.</p><button onClick={()=>go('Preferences')}>Manage alerts</button></div></aside></div></>;
}

function DetailContent({tab,job}:{tab:string;job:Job}){if(tab==='Job description')return <div className="detail-pane"><h4>Role summary</h4><p>Work with the {job.company} engineering team on production projects. Review the official posting for current responsibilities, eligibility, dates, and location requirements.</p><div className="keyword-cloud">{job.tags.map(t=><span key={t}>{t}</span>)}</div></div>;if(tab==='People & resumes')return <div className="detail-pane"><h4>People & public resources</h4><p>No verified former-intern profiles or public resumes are attached yet. Orbit will only show publicly available, verifiable sources.</p></div>;if(tab==='Company signal')return <div className="detail-pane"><h4>Company direction</h4><p>{job.company} is investing in developer productivity, reliable infrastructure, and AI-assisted product experiences. This is a directional signal, not hiring advice.</p></div>;return <><div className="insight-callout"><Sparkles size={17}/><div><strong>Why this is a strong match</strong><p>The role overlaps with your selected engineering interests and emphasizes {job.tags.join(', ')}.</p></div></div><div className="two-col"><div><h4>What matters</h4><ul className="check-list"><li>Build production-quality software</li><li>Collaborate across engineering teams</li><li>Learn through meaningful ownership</li></ul></div><div><h4>Important keywords</h4><div className="keyword-cloud">{job.tags.map(t=><span key={t}>{t}</span>)}</div></div></div></>}

function Applications({apps,openForm,updateStatus,removeApp}:{apps:Application[];openForm:(j?:Job,s?:Status)=>void;updateStatus:(id:string,s:Status)=>void;removeApp:(id:string)=>void}){const applied=apps.filter(a=>a.status!=='Saved').length;return <><div className="page-heading"><div><p className="eyebrow">APPLICATION WORKSPACE</p><h1>Applications</h1><p>One place for every deadline, follow-up, and outcome.</p></div><button className="primary-button" onClick={()=>openForm()}>+ Add application</button></div><div className="tracker-summary"><div><b>{apps.length}</b><span>Total tracked</span></div><div><b>{applied}</b><span>Applications sent</span></div><div><b>—</b><span>Interview rate</span></div><div><b>0</b><span>Actions due</span></div></div>{apps.length===0&&<div className="empty-state"><BriefcaseBusiness size={24}/><h2>No applications yet</h2><p>Add your first application or save a role from Discover.</p><button className="primary-button" onClick={()=>openForm()}>Add first application</button></div>}<div className="kanban">{statuses.map(status=>{const cards=apps.filter(a=>a.status===status);return <section className="kanban-col" key={status}><header><span><i/> {status}</span><b>{cards.length}</b></header>{cards.map(a=><article className="application-card" key={a.id}><div><span className="tiny-logo">{a.company[0]}</span><b>{a.company}</b><button aria-label="Remove application" onClick={()=>removeApp(a.id)}>×</button></div><h3>{a.role}</h3><p>{a.location||'Location not added'}</p><footer><select aria-label={`Status for ${a.company}`} value={a.status} onChange={e=>updateStatus(a.id,e.target.value as Status)}>{statuses.map(s=><option key={s}>{s}</option>)}</select><span>{a.updated}</span></footer></article>)}<button className="add-card" onClick={()=>openForm(undefined,status)}>+ Add application</button></section>})}</div></>}

function Overview({apps}:{apps:Application[]}){const sent=apps.filter(a=>a.status!=='Saved').length;return <><div className="page-heading"><div><p className="eyebrow">SEARCH PERFORMANCE</p><h1>Your search, at a glance</h1><p>Signals that help you spend time on the right opportunities.</p></div></div><div className="overview-cards"><div><span>Relevant roles found</span><b>{jobs.length}</b><em>Current sample feed</em></div><div><span>Applications sent</span><b>{sent}</b><em>{sent?'Tracking your progress':'No applications yet'}</em></div><div><span>Interview rate</span><b>—</b><em>Available after your first response</em></div><div><span>Saved roles</span><b>{apps.filter(a=>a.status==='Saved').length}</b><em>Ready to review</em></div></div></>}

function Preferences({toast}:{toast:(x:string)=>void}){const [days,setDays]=useState('365');const [alerts,setAlerts]=useState(true);const [duplicates,setDuplicates]=useState(true);return <><div className="page-heading"><div><p className="eyebrow">WORKSPACE SETTINGS</p><h1>Preferences</h1><p>Control your search, alerts, and data lifecycle.</p></div></div><div className="settings-card"><section><div><h3>Data retention</h3><p>Choose how long closed applications remain on this device.</p></div><select value={days} onChange={e=>{setDays(e.target.value);toast('Retention preference saved')}}><option value="90">90 days</option><option value="180">180 days</option><option value="365">1 year</option><option value="forever">Keep until I delete</option></select></section><section><div><h3>Discovery refresh</h3><p>Scan supported public job sources for new roles.</p></div><span className="setting-value">Every 30 minutes</span></section><section><div><h3>Duplicate detection</h3><p>Merge reposted roles across sources.</p></div><button aria-label="Toggle duplicate detection" className={duplicates?'toggle on':'toggle'} onClick={()=>{setDuplicates(!duplicates);toast('Duplicate detection updated')}}><i/></button></section><section><div><h3>Opportunity alerts</h3><p>Highlight strong matches and closing roles.</p></div><button aria-label="Toggle alerts" className={alerts?'toggle on':'toggle'} onClick={()=>{setAlerts(!alerts);toast('Alert preference updated')}}><i/></button></section></div></>}

function SimplePage({name,go}:{name:string;go:(x:string)=>void}){const copy:Record<string,string>={Watchlists:'Saved searches and companies you follow will appear here.',People:'Verified public profiles connected to roles will appear here.',Documents:'Resumes, cover letters, and application documents will appear here.'};return <><div className="page-heading"><div><p className="eyebrow">ORBIT WORKSPACE</p><h1>{name}</h1><p>{copy[name]}</p></div></div><div className="empty-state"><h2>Your {name.toLowerCase()} space is ready</h2><p>Start from Discover and Orbit will organize relevant items here.</p><button className="primary-button" onClick={()=>go('Discover')}>Browse opportunities</button></div></>}
